apiVersion: v1
kind: ServiceAccount
metadata:
  name: pulumi-auth
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pulumi-cr
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - "traefik.io"
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - apps
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - networking.k8s.io
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pulumi-crb
subjects:
- kind: ServiceAccount
  name: pulumi-pulumi-kubernetes-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: pulumi-cr
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    meta.helm.sh/release-name: pulumi
    meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/instance: pulumi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pulumi-kubernetes-operator
    app.kubernetes.io/version: 1.14.0
    helm.sh/chart: pulumi-kubernetes-operator-0.7.3
  name: pulumi-pulumi-kubernetes-operator
  namespace: default
rules:
- apiGroups:
  - ""
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - "traefik.io"
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - apps
  resources: ["*"]
  verbs: ["*"]
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - pulumi.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
