apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{"meta.helm.sh/release-name":"pulumi","meta.helm.sh/release-namespace":"default"},"labels":{"app.kubernetes.io/instance":"pulumi","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"pulumi-kubernetes-operator","app.kubernetes.io/version":"1.14.0","helm.sh/chart":"pulumi-kubernetes-operator-0.7.3"},"name":"pulumi-pulumi-kubernetes-operator","namespace":"default"},"rules":[{"apiGroups":[""],"resources":["*"],"verbs":["*"]},{"apiGroups":["traefik.io"],"resources":["*"],"verbs":["*"]},{"apiGroups":["apps"],"resources":["*"],"verbs":["*"]},{"apiGroups":["monitoring.coreos.com"],"resources":["servicemonitors"],"verbs":["get","create"]},{"apiGroups":["apps"],"resourceNames":["pulumi-kubernetes-operator"],"resources":["deployments/finalizers"],"verbs":["update"]},{"apiGroups":[""],"resources":["pods"],"verbs":["get"]},{"apiGroups":["apps"],"resources":["replicasets","deployments"],"verbs":["get"]},{"apiGroups":["pulumi.com"],"resources":["*"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["coordination.k8s.io"],"resources":["leases"],"verbs":["create","get","list","update"]},{"apiGroups":["source.toolkit.fluxcd.io"],"resources":["*"],"verbs":["get","list","watch"]}]}
    meta.helm.sh/release-name: pulumi
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2024-04-28T14:27:44Z"
  labels:
    app.kubernetes.io/instance: pulumi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pulumi-kubernetes-operator
    app.kubernetes.io/version: 1.14.0
    helm.sh/chart: pulumi-kubernetes-operator-0.7.3
  managedFields:
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/instance: {}
          f:app.kubernetes.io/managed-by: {}
          f:app.kubernetes.io/name: {}
          f:app.kubernetes.io/version: {}
          f:helm.sh/chart: {}
    manager: helm
    operation: Update
    time: "2024-04-28T14:27:44Z"
  - apiVersion: rbac.authorization.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:rules: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2024-04-28T14:28:58Z"
  name: pulumi-pulumi-kubernetes-operator
  namespace: default
  resourceVersion: "5949"
  uid: 3dc1711c-b2c6-418e-b799-3f65a37d7cc9
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - traefik.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - pulumi-kubernetes-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - pulumi.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
